CREATE TABLE `ITEM_TYPE` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL UNIQUE,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ITEM` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`TYPE_ID` varchar(25) NOT NULL,
	`NAME` varchar(50) NOT NULL UNIQUE,
	`DISPLAY_NAME` varchar(100) NOT NULL,
	`DESCRIPTION` varchar(500) NOT NULL,
	`ITEM_IMAGE_ID` varchar(25) NOT NULL,
	`PRICE` FLOAT(10) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ITEM_IMAGE` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`ITEM_ID` varchar(25) NOT NULL,
	`IMAGE_ID` varchar(25) NOT NULL,
	`TYPE` varchar(50) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `IMAGE` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`IMAGE` varchar(100) NOT NULL UNIQUE,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SYSTEM_USER` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`USERNAME` varchar(50) NOT NULL UNIQUE,
	`PASSWORD` varchar(500) NOT NULL,
	`COUNTER` INT(10) NOT NULL DEFAULT '0',
	`LAST_LOGING` DATETIME NOT NULL,
	`IS_ADMIN` BINARY(1) NOT NULL DEFAULT '0',
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_DETAILS` (
	`USER_ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`AVATAR_IMAGE_ID` varchar(25) NOT NULL UNIQUE,
	`FIRST_NAME` varchar(200) NOT NULL,
	`LAST_NAME` varchar(200) NOT NULL,
	`ADDRESS` varchar(500) NOT NULL,
	`EMAIL` varchar(250) NOT NULL UNIQUE,
	`TEL` varchar(20) NOT NULL UNIQUE,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `AVATAR_IMAGE` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`IMAGE` varchar(500) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `QUANTITY` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`ITEM_ID` varchar(25) NOT NULL UNIQUE,
	`QUANTITY` INT(10) NOT NULL,
	`STOCK_ID` INT(10) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `STOCK` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`ITEM_ID` varchar(25) NOT NULL UNIQUE,
	`QUANTITY` INT(10) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `BASKET` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`ITEM_ID` varchar(25) NOT NULL UNIQUE,
	`USER_ID` varchar(25) NOT NULL,
	`IS_PERCHES` BINARY(1) NOT NULL DEFAULT '0',
	`PRICE` FLOAT(10) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PERCHES` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`BASKET_ID` varchar(25) NOT NULL UNIQUE,
	`USER_ID` varchar(25) NOT NULL,
	`STOCK_ID` varchar(25) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ORDER` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`PERCHES_ID` varchar(25) NOT NULL UNIQUE,
	`USER_ID` varchar(25) NOT NULL,
	`STOCK_ID` varchar(25) NOT NULL,
	`IS_DONE` BINARY(1) NOT NULL DEFAULT '0',
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ISSUE` (
	`ID` varchar(25) NOT NULL AUTO_INCREMENT,
	`ORDER_ID` varchar(25) NOT NULL UNIQUE,
	`USER_ID` varchar(25) NOT NULL,
	`STOCK_ID` varchar(25) NOT NULL,
	`CREATED_BY` varchar(25) NOT NULL,
	`CREATED_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATED_BY` varchar(25),
	`LAST_UPDATED_TIME` DATETIME,
	`DELETED` BINARY(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
);

ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_fk0` FOREIGN KEY (`TYPE_ID`) REFERENCES `ITEM_TYPE`(`ID`);

ALTER TABLE `ITEM_IMAGE` ADD CONSTRAINT `ITEM_IMAGE_fk0` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`);

ALTER TABLE `ITEM_IMAGE` ADD CONSTRAINT `ITEM_IMAGE_fk1` FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`ID`);

ALTER TABLE `USER_DETAILS` ADD CONSTRAINT `USER_DETAILS_fk0` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_USER`(`ID`);

ALTER TABLE `AVATAR_IMAGE` ADD CONSTRAINT `AVATAR_IMAGE_fk0` FOREIGN KEY (`ID`) REFERENCES `USER_DETAILS`(`AVATAR_IMAGE_ID`);

ALTER TABLE `QUANTITY` ADD CONSTRAINT `QUANTITY_fk0` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`);

ALTER TABLE `QUANTITY` ADD CONSTRAINT `QUANTITY_fk1` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`);

ALTER TABLE `STOCK` ADD CONSTRAINT `STOCK_fk0` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`);

ALTER TABLE `BASKET` ADD CONSTRAINT `BASKET_fk0` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM`(`ID`);

ALTER TABLE `BASKET` ADD CONSTRAINT `BASKET_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_USER`(`ID`);

ALTER TABLE `PERCHES` ADD CONSTRAINT `PERCHES_fk0` FOREIGN KEY (`BASKET_ID`) REFERENCES `BASKET`(`ID`);

ALTER TABLE `PERCHES` ADD CONSTRAINT `PERCHES_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_USER`(`ID`);

ALTER TABLE `PERCHES` ADD CONSTRAINT `PERCHES_fk2` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`);

ALTER TABLE `ORDER` ADD CONSTRAINT `ORDER_fk0` FOREIGN KEY (`PERCHES_ID`) REFERENCES `PERCHES`(`ID`);

ALTER TABLE `ORDER` ADD CONSTRAINT `ORDER_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_USER`(`ID`);

ALTER TABLE `ORDER` ADD CONSTRAINT `ORDER_fk2` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`);

ALTER TABLE `ISSUE` ADD CONSTRAINT `ISSUE_fk0` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ID`);

ALTER TABLE `ISSUE` ADD CONSTRAINT `ISSUE_fk1` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_USER`(`ID`);

ALTER TABLE `ISSUE` ADD CONSTRAINT `ISSUE_fk2` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`);

